---

### The Ansible Galaxy requirements file
# Specifies the collections and roles that should be installed
# in this Ansible workspace.


## Collections requirements
collections:
  - ansible.posix
  - community.general

## Roles requirements
roles:
  - name: robertdebock.users
    version: 6.1.8
  - name: ansible-suite.ssh_keys
    src: git+https://github.com/ansible-suite/ansible-role-ssh-keys.git
  - name: ansible-suite.packages
    src: git+https://github.com/ansible-suite/ansible-role-packages.git
  - name: ansible-suite.qemu_guest_agent
    src: git+https://github.com/ansible-suite/ansible-role-qemu-guest-agent.git
  - name: ansible-suite.smb_mounts
    src: git+https://github.com/ansible-suite/ansible-role-smb-mounts.git
  - name: ansible-suite.deb_packages
    src: git+https://github.com/ansible-suite/ansible-role-deb_packages.git
  - name: ansible-suite.apt_thirdparty
    src: git+https://github.com/ansible-suite/ansible-role-apt_thirdparty.git
  - name: ansible-suite.snap_packages
    src: git+https://github.com/ansible-suite/ansible-role-snap_packages.git
  - name: ansible-tul.openssh
    src: git+git@gitlab.tul.cz:ansible-tul/ansible-collections/ansible-role-openssh.git
  - name: ansible-tul.ntp
    src: git+git@gitlab.tul.cz:ansible-tul/ansible-collections/ansible-role-ntp.git
  - name: ansible-tul.fail2ban
    src: git+git@gitlab.tul.cz:ansible-tul/ansible-collections/ansible-role-fail2ban.git
  - name: ansible-tul.update_packages
    src: git+git@gitlab.tul.cz:ansible-tul/ansible-collections/ansible-role-update-packages.git
  - name: ansible-tul.automatic_updates
    src: git+git@gitlab.tul.cz:ansible-tul/ansible-collections/ansible-role-automatic-updates.git
