[local]
localhost ansible_connection=local ansible_user=ansible

[workstations]
p330 ansible_host=192.168.1.17 ansible_user=ansible
x220 ansible_host=192.168.1.31 ansible_user=ansible
Asus ansible_host=192.168.1.34 ansible_user=ansible
Dell_5450 ansible_host=192.168.1.67 ansible_user=ansible

[n900]
N900 ansible_host=192.168.1.51 ansible_user=user

[VMs]
Docker-runner ansible_host=192.168.1.88 ansible_user=ansible

[physical_servers]
Zalman ansible_host=192.168.1.100 ansible_user=ansible

[servers:children]
physical_servers
VMs

[hosts:children]
local
n900
workstations
servers

[other]
Bazzite ansible_host=192.168.1.84 ansible_user=ansible