---
# ============================================
# SSH KEYS
# ============================================

ssh_keys_exclusive: false
ssh_keys_state: present

ssh_keys_authorized:
  - user: ansible
    key_owners:
      - ansible

  - user: pytel
    key_owners:
      - jaroslav.korner

# ============================================
# One-time system updates
# ============================================

update_packages_autoremove: true

# ============================================
# PACKAGES
# ============================================

snap_packages:
  - tpad
  - mission-center
  - code
  - opera

ranger_devicons_enabled: false
