---
# ============================================
# SSH KEYS
# ============================================

ssh_keys_exclusive: false
ssh_keys_state: present

ssh_keys_authorized:
  - user: ansible
    key_owners:
      - ansible

  - user: pytel
    key_owners:
      - jaroslav.korner

# ============================================
# One-time system updates
# ============================================

update_packages_autoremove: true

# ============================================
# PACKAGES
# ============================================

packages:
  - vim
  - nala
  - aptitude
  - git
  - curl
  - wget
  - tmux
  - cron
  - entr
  - vlc
  - gimp
  - gparted
  - p7zip-full
  - cmatrix
  - odt2txt
  - grsync
  - htop
  - cbonsai
  - ripgrep

snap_packages:
  - tpad
  - mission-center
  - code

ranger_devicons_enabled: false
