---
- name: Nasazení Portainer stacku
  hosts: Docker-runner
  become: true

  vars:
    stack_name: portainer
    stack_path: /opt/docker-stacks/portainer
    source_path: ../../../compose-stacks/portainer
    owner_uid: 1109
    owner_gid: 2000

  tasks:

    - name: Vytvoření lokální složky pro compose stack a konfiguraci
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ owner_uid }}"
        group: "{{ owner_gid }}"
        mode: "0775"
      loop:
        - "{{ stack_path }}"
        - "{{ stack_path }}/data"

    - name: Kopírování docker-compose.yml na server
      ansible.builtin.copy:
        src: "{{ source_path }}/docker-compose.yml"
        dest: "{{ stack_path }}/docker-compose.yml"
        owner: ansible
        group: ansible
        mode: "0644"

    - name: Instalace systemd služby
      ansible.builtin.template:
        src: "{{ source_path }}/docker-compose.service.j2"
        dest: "/etc/systemd/system/{{ stack_name }}.service"
        owner: root
        group: root
        mode: "0644"
      notify:
        - Reload systemd

    - name: Povolení a spuštění Portainer služby
      ansible.builtin.systemd:
        name: "{{ stack_name }}.service"
        daemon_reload: true
        enabled: true
        state: started

  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true
