---

fail2ban_enabled: true
fail2ban_bantime: 5h

# ============================================
# USERS
# ============================================

users:
  - name: ansible
    groups:
      - sudo

  - name: pytel
    password: ''
    update_password: on_create
    groups:
      - sudo

# ============================================
# SSH KEYS
# ============================================

ssh_keys_exclusive: false
ssh_keys_state: present

ssh_keys_authorized:
  - user: ansible
    key_owners:
      - ansible

  - user: pytel
    key_owners:
      - jaroslav.korner

# ============================================
# UPDATE PACKAGES
# ============================================

# Supported values: manual, cache_only, unattended
system_update_mode: unattended

# needrestart behavior on Debian based systems
# Options: a (auto) l (list) i (interactive)
system_update_debian_needrestart_enabled: true
system_update_debian_needrestart_mode: "a"

# List of allowed origins for unattended upgrades
system_update_unattended_origins:
  - "${distro_id}:${distro_codename}"
  - "${distro_id}:${distro_codename}-security"
  - "${distro_id}:${distro_codename}-updates"

# ============================================
# PACKAGES
# ============================================

packages:
  - vim
  - htop
  - curl
