# ============================================
# UPDATE PACKAGES
# ============================================

# Package cleanup and reboot policy for unattended updates.
system_update_remove_unused_dependencies: true
system_update_automatic_reboot: true

system_update_automatic_reboot_time: "02:00"

# ============================================
# NTP SERVERS
# ============================================

ntp_configuration_ntp_servers:
  - tik.cesnet.cz
  - tak.cesnet.cz
  - ntp.nic.cz

# ============================================
# PACKAGES
# ============================================

packages:
  - git

packages_remove:
  - telnet
  - avahi-daemon
  - modemmanager
  - rsh-client
  - rsh-server
  - rlogin